sudo: false
env:
  global:
  - secure: A4hLh8CQbeTWIittGJu3O9nlytxhiSFGtuTqfKt+LNPwOYWzsVa/xZ8PQeWv/UzpQMvIVvQ7BYCqo+Ed4i12Y0bn87w6F0LRQA1TrVXEeJf+b41B8G/KuxhiNKo9Wlsou5AfIEPDUFlFbtviZYHC2mROxv+2mkiWdTYEEfkDhcY=
language: python
python:
- 2.6
- 2.7
- 3.2
- 3.3
- 3.4
- pypy
install:
- pip install pytest
- pip install requests
- pip install coveralls
script:
- coverage run --source=travispy setup.py test
after_success:
- coveralls
