sudo: false
language: python
python:
- 2.7
- 3.4
- 3.5
- 3.6
- pypy
install:
- pip install pytest
- pip install pytest-rerunfailures
- pip install requests
- pip install coveralls
script:
- coverage run --source=travispy setup.py test -a -rxs
after_success:
- coveralls
